/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz.de.usuario;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.*;



/**
 *
 * @author yanyg
 */
public class pruebaImagen extends javax.swing.JFrame {
 
   
    public pruebaImagen() {
        initComponents();
        
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        btnSalir = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MenuFile = new javax.swing.JMenu();
        menuCerrar = new javax.swing.JMenuItem();
        menuRegistro = new javax.swing.JMenu();
        itemMenuRegistroEstudiante = new javax.swing.JMenuItem();
        itemMenuRegistroDocente = new javax.swing.JMenuItem();
        menuAyuda = new javax.swing.JMenu();
        menuSobreNosotros = new javax.swing.JMenu();
        itemMenuUcompensar = new javax.swing.JMenuItem();
        itemMenuCreadores = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Desktop.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 840, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        getContentPane().add(Desktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, 480));

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 200, -1, -1));

        MenuFile.setText("File");

        menuCerrar.setText("Cerrar");
        menuCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuCerrarActionPerformed(evt);
            }
        });
        MenuFile.add(menuCerrar);

        jMenuBar1.add(MenuFile);

        menuRegistro.setText("Registro");

        itemMenuRegistroEstudiante.setText("Estudiante");
        itemMenuRegistroEstudiante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuRegistroEstudianteActionPerformed(evt);
            }
        });
        menuRegistro.add(itemMenuRegistroEstudiante);

        itemMenuRegistroDocente.setText("Docente");
        itemMenuRegistroDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemMenuRegistroDocenteActionPerformed(evt);
            }
        });
        menuRegistro.add(itemMenuRegistroDocente);

        jMenuBar1.add(menuRegistro);

        menuAyuda.setText("Ayuda");

        menuSobreNosotros.setText("Sobre nosotros");

        itemMenuUcompensar.setText("UCompensar");
        menuSobreNosotros.add(itemMenuUcompensar);

        itemMenuCreadores.setText("Desarrolladores de la app");
        menuSobreNosotros.add(itemMenuCreadores);

        menuAyuda.add(menuSobreNosotros);

        jMenuBar1.add(menuAyuda);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
        //System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void itemMenuRegistroDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuRegistroDocenteActionPerformed
        // TODO add your handling code here:
        RegistroDocentes rD = new RegistroDocentes();
        rD.setVisible(true);
        
    }//GEN-LAST:event_itemMenuRegistroDocenteActionPerformed

    private void itemMenuRegistroEstudianteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemMenuRegistroEstudianteActionPerformed
        // Creamos un objeto de nuestra interfaz
        RegistroEstudiantes re = new RegistroEstudiantes();
        Desktop.add(re);
        re.show();
    }//GEN-LAST:event_itemMenuRegistroEstudianteActionPerformed

    private void menuCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCerrarActionPerformed
        System.exit(0);
    }//GEN-LAST:event_menuCerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pruebaImagen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pruebaImagen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pruebaImagen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pruebaImagen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pruebaImagen().setVisible(true);
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenu MenuFile;
    private javax.swing.JButton btnSalir;
    private javax.swing.JMenuItem itemMenuCreadores;
    private javax.swing.JMenuItem itemMenuRegistroDocente;
    private javax.swing.JMenuItem itemMenuRegistroEstudiante;
    private javax.swing.JMenuItem itemMenuUcompensar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuAyuda;
    private javax.swing.JMenuItem menuCerrar;
    private javax.swing.JMenu menuRegistro;
    private javax.swing.JMenu menuSobreNosotros;
    // End of variables declaration//GEN-END:variables
}
